[package]
name = "simple-fantasy-game"
version = "0.1.1"
edition = "2021"

[dependencies]
console-utils = "1.7.0"
rand = { version = "0.9.0", features = ["small_rng"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
